name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: jhdemo pipeline
        runs-on: ubuntu-20.04
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.16.1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Install node.js packages
              run: |
                java -version
                npm install
            - name: Run backend test
              run: |
                  java -version
                  #chmod +x mvnw
                  mvn -ntp clean verify -P-webpack
              env:
                NODE_VERSION: 12.16.1
            - name: Run frontend test
              run: |
                  java -version
                  npm run test
            - uses: actions/setup-java@v1
              with:
                 java-version: 11
            - name: Analyze code with SonarQube
              continue-on-error: true
              env:
                  GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  java -version
                  if [ -n $SONAR_TOKEN ]; then
                      mvn -ntp initialize sonar:sonar -Dsonar.organization=${{ secrets.SONAR_ORGANISATION_KEY }} -Dsonar.host.url=${{ secrets.SONAR_URL }}
                  else
                      echo No SONAR_TOKEN, skipping...
                  fi
            - name: Package application
              continue-on-error: true
              env:
                maven-local-repo-path: ${{secrets.JFROG_OSS_REPO_SNAPSHOTS }}
                maven-repo-server-id: snapshots
                maven-repo-server-username: ${{ secrets.JFROG_OSS_REPO_USER }}
                maven-repo-server-password: ${{ secrets.JFROG_OSS_REPO_PASS }}
              run: |
                  cat ~/.m2/settings.xml
                  ./mvnw -ntp package deploy -Pprod -DskipTests
                
    
    #https://github.com/marketplace/actions/deploy-to-heroku  
    jobdeploy:
      name: Deploy to Herroku
      needs: pipeline
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            branch: "master"
            buildpack: ${{secrets.HEROKU_BUILD_PACK}}
