name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: biblio pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.16.1
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Install node.js packages
              run: npm install
            - name: Run backend test
              run: |
                  chmod +x mvnw
                  ./mvnw -ntp clean verify -P-webpack
            - name: Run frontend test
              run: npm run test
              continue-on-error: true
            - name: Analyze code with SonarQube
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  if [ -n $SONAR_TOKEN ]; then
                      mvn -ntp initialize sonar:sonar -Dsonar.organization=dassoukhi-1 -Dsonar.host.url=https://sonarcloud.io
                  else
                      echo No SONAR_TOKEN, skipping...
                  fi
              continue-on-error: true    
            - name: Package application
              run: mvn -ntp package deploy -Pprod -DskipTests
              continue-on-error: true
            - name: Deploy to Heroku
              if: github.event_name == 'push' && github.ref == 'refs/heads/master'
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              run: mvn -ntp com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod -Dheroku.buildpacks=heroku/jvm -Dheroku.appName=biblioprojet
